export const SAVE_CONTENT = 'SAVE_CONTENT';
export const GET_LOCAL_CONTENT = 'GET_LOCAL_CONTENT';
export const STORE_SUCCESS = 'STORE_SUCCESS';
export const STORE_FAIL = 'STORE_FAIL';

export const FETCH_POSTS_START = 'FETCH_POSTS_START';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_FAIL = 'FETCH_POSTS_FAIL';