export const SAVE_CONTENT = 'SAVE_CONTENT';
export const GET_LOCAL_CONTENT = 'GET_LOCAL_CONTENT';
export const STORE_START = 'STORE_START';
export const STORE_SUCCESS = 'STORE_SUCCESS';
export const STORE_FAIL = 'STORE_FAIL';
export const NULLIFY_REDIRECT = 'NULLIFY_REDIRECT';

export const FETCH_POSTS_START = 'FETCH_POSTS_START';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_FAIL = 'FETCH_POSTS_FAIL';
export const GET_NOTE_CONTENT = 'GET_NOTE_CONTENT';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'LOGOUT';